// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: base.proto
// Protobuf C++ Version: 5.29.5

#include "base.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr SkillItem::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : skill_id_{0u},
        level_{0},
        key_pos_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SkillItem::SkillItem(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SkillItemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SkillItemDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SkillItemDefaultTypeInternal() {}
  union {
    SkillItem _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SkillItemDefaultTypeInternal _SkillItem_default_instance_;

inline constexpr ItemData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : item_id_{0},
        item_num_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ItemData::ItemData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ItemDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ItemDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ItemDataDefaultTypeInternal() {}
  union {
    ItemData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ItemDataDefaultTypeInternal _ItemData_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_base_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_base_2eproto = nullptr;
const ::uint32_t
    TableStruct_base_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ItemData, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ItemData, _impl_.item_id_),
        PROTOBUF_FIELD_OFFSET(::ItemData, _impl_.item_num_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::SkillItem, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::SkillItem, _impl_.skill_id_),
        PROTOBUF_FIELD_OFFSET(::SkillItem, _impl_.level_),
        PROTOBUF_FIELD_OFFSET(::SkillItem, _impl_.key_pos_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ItemData)},
        {10, -1, -1, sizeof(::SkillItem)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_ItemData_default_instance_._instance,
    &::_SkillItem_default_instance_._instance,
};
const char descriptor_table_protodef_base_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nbase.proto\"-\n\010ItemData\022\017\n\007item_id\030\001 \001("
    "\005\022\020\n\010item_num\030\002 \001(\005\"=\n\tSkillItem\022\020\n\010skil"
    "l_id\030\001 \001(\r\022\r\n\005level\030\002 \001(\005\022\017\n\007key_pos\030\003 \001"
    "(\005b\006proto3"
};
static ::absl::once_flag descriptor_table_base_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_base_2eproto = {
    false,
    false,
    130,
    descriptor_table_protodef_base_2eproto,
    "base.proto",
    &descriptor_table_base_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_base_2eproto::offsets,
    file_level_enum_descriptors_base_2eproto,
    file_level_service_descriptors_base_2eproto,
};
// ===================================================================

class ItemData::_Internal {
 public:
};

ItemData::ItemData(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ItemData)
}
ItemData::ItemData(
    ::google::protobuf::Arena* arena, const ItemData& from)
    : ItemData(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ItemData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ItemData::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, item_id_),
           0,
           offsetof(Impl_, item_num_) -
               offsetof(Impl_, item_id_) +
               sizeof(Impl_::item_num_));
}
ItemData::~ItemData() {
  // @@protoc_insertion_point(destructor:ItemData)
  SharedDtor(*this);
}
inline void ItemData::SharedDtor(MessageLite& self) {
  ItemData& this_ = static_cast<ItemData&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ItemData::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ItemData(arena);
}
constexpr auto ItemData::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ItemData),
                                            alignof(ItemData));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ItemData::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ItemData_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ItemData::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ItemData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ItemData::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ItemData>(), &ItemData::ByteSizeLong,
            &ItemData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ItemData, _impl_._cached_size_),
        false,
    },
    &ItemData::kDescriptorMethods,
    &descriptor_table_base_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ItemData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> ItemData::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ItemData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 item_num = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ItemData, _impl_.item_num_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ItemData, _impl_.item_num_)}},
    // int32 item_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ItemData, _impl_.item_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ItemData, _impl_.item_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 item_id = 1;
    {PROTOBUF_FIELD_OFFSET(ItemData, _impl_.item_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 item_num = 2;
    {PROTOBUF_FIELD_OFFSET(ItemData, _impl_.item_num_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ItemData::Clear() {
// @@protoc_insertion_point(message_clear_start:ItemData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.item_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.item_num_) -
      reinterpret_cast<char*>(&_impl_.item_id_)) + sizeof(_impl_.item_num_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ItemData::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ItemData& this_ = static_cast<const ItemData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ItemData::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ItemData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ItemData)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 item_id = 1;
          if (this_._internal_item_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_item_id(), target);
          }

          // int32 item_num = 2;
          if (this_._internal_item_num() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_item_num(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ItemData)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ItemData::ByteSizeLong(const MessageLite& base) {
          const ItemData& this_ = static_cast<const ItemData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ItemData::ByteSizeLong() const {
          const ItemData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ItemData)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 item_id = 1;
            if (this_._internal_item_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_item_id());
            }
            // int32 item_num = 2;
            if (this_._internal_item_num() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_item_num());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ItemData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ItemData*>(&to_msg);
  auto& from = static_cast<const ItemData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ItemData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_item_id() != 0) {
    _this->_impl_.item_id_ = from._impl_.item_id_;
  }
  if (from._internal_item_num() != 0) {
    _this->_impl_.item_num_ = from._impl_.item_num_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ItemData::CopyFrom(const ItemData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ItemData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ItemData::InternalSwap(ItemData* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ItemData, _impl_.item_num_)
      + sizeof(ItemData::_impl_.item_num_)
      - PROTOBUF_FIELD_OFFSET(ItemData, _impl_.item_id_)>(
          reinterpret_cast<char*>(&_impl_.item_id_),
          reinterpret_cast<char*>(&other->_impl_.item_id_));
}

::google::protobuf::Metadata ItemData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SkillItem::_Internal {
 public:
};

SkillItem::SkillItem(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:SkillItem)
}
SkillItem::SkillItem(
    ::google::protobuf::Arena* arena, const SkillItem& from)
    : SkillItem(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SkillItem::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SkillItem::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, skill_id_),
           0,
           offsetof(Impl_, key_pos_) -
               offsetof(Impl_, skill_id_) +
               sizeof(Impl_::key_pos_));
}
SkillItem::~SkillItem() {
  // @@protoc_insertion_point(destructor:SkillItem)
  SharedDtor(*this);
}
inline void SkillItem::SharedDtor(MessageLite& self) {
  SkillItem& this_ = static_cast<SkillItem&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SkillItem::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SkillItem(arena);
}
constexpr auto SkillItem::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SkillItem),
                                            alignof(SkillItem));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SkillItem::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SkillItem_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SkillItem::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SkillItem>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SkillItem::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SkillItem>(), &SkillItem::ByteSizeLong,
            &SkillItem::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SkillItem, _impl_._cached_size_),
        false,
    },
    &SkillItem::kDescriptorMethods,
    &descriptor_table_base_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SkillItem::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> SkillItem::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::SkillItem>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 skill_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SkillItem, _impl_.skill_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SkillItem, _impl_.skill_id_)}},
    // int32 level = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SkillItem, _impl_.level_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(SkillItem, _impl_.level_)}},
    // int32 key_pos = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SkillItem, _impl_.key_pos_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(SkillItem, _impl_.key_pos_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 skill_id = 1;
    {PROTOBUF_FIELD_OFFSET(SkillItem, _impl_.skill_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // int32 level = 2;
    {PROTOBUF_FIELD_OFFSET(SkillItem, _impl_.level_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 key_pos = 3;
    {PROTOBUF_FIELD_OFFSET(SkillItem, _impl_.key_pos_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void SkillItem::Clear() {
// @@protoc_insertion_point(message_clear_start:SkillItem)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.skill_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.key_pos_) -
      reinterpret_cast<char*>(&_impl_.skill_id_)) + sizeof(_impl_.key_pos_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SkillItem::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SkillItem& this_ = static_cast<const SkillItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SkillItem::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SkillItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:SkillItem)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 skill_id = 1;
          if (this_._internal_skill_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_skill_id(), target);
          }

          // int32 level = 2;
          if (this_._internal_level() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_level(), target);
          }

          // int32 key_pos = 3;
          if (this_._internal_key_pos() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_key_pos(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:SkillItem)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SkillItem::ByteSizeLong(const MessageLite& base) {
          const SkillItem& this_ = static_cast<const SkillItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SkillItem::ByteSizeLong() const {
          const SkillItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:SkillItem)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint32 skill_id = 1;
            if (this_._internal_skill_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_skill_id());
            }
            // int32 level = 2;
            if (this_._internal_level() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_level());
            }
            // int32 key_pos = 3;
            if (this_._internal_key_pos() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_key_pos());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SkillItem::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SkillItem*>(&to_msg);
  auto& from = static_cast<const SkillItem&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SkillItem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_skill_id() != 0) {
    _this->_impl_.skill_id_ = from._impl_.skill_id_;
  }
  if (from._internal_level() != 0) {
    _this->_impl_.level_ = from._impl_.level_;
  }
  if (from._internal_key_pos() != 0) {
    _this->_impl_.key_pos_ = from._impl_.key_pos_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SkillItem::CopyFrom(const SkillItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SkillItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SkillItem::InternalSwap(SkillItem* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SkillItem, _impl_.key_pos_)
      + sizeof(SkillItem::_impl_.key_pos_)
      - PROTOBUF_FIELD_OFFSET(SkillItem, _impl_.skill_id_)>(
          reinterpret_cast<char*>(&_impl_.skill_id_),
          reinterpret_cast<char*>(&other->_impl_.skill_id_));
}

::google::protobuf::Metadata SkillItem::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_base_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
