// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: base.proto
// Protobuf C++ Version: 5.29.5

#ifndef base_2eproto_2epb_2eh
#define base_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_base_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_base_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_base_2eproto;
class ItemData;
struct ItemDataDefaultTypeInternal;
extern ItemDataDefaultTypeInternal _ItemData_default_instance_;
class SkillItem;
struct SkillItemDefaultTypeInternal;
extern SkillItemDefaultTypeInternal _SkillItem_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class SkillItem final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:SkillItem) */ {
 public:
  inline SkillItem() : SkillItem(nullptr) {}
  ~SkillItem() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SkillItem* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SkillItem));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SkillItem(
      ::google::protobuf::internal::ConstantInitialized);

  inline SkillItem(const SkillItem& from) : SkillItem(nullptr, from) {}
  inline SkillItem(SkillItem&& from) noexcept
      : SkillItem(nullptr, std::move(from)) {}
  inline SkillItem& operator=(const SkillItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline SkillItem& operator=(SkillItem&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SkillItem& default_instance() {
    return *internal_default_instance();
  }
  static inline const SkillItem* internal_default_instance() {
    return reinterpret_cast<const SkillItem*>(
        &_SkillItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SkillItem& a, SkillItem& b) { a.Swap(&b); }
  inline void Swap(SkillItem* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SkillItem* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SkillItem* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SkillItem>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SkillItem& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SkillItem& from) { SkillItem::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SkillItem* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "SkillItem"; }

 protected:
  explicit SkillItem(::google::protobuf::Arena* arena);
  SkillItem(::google::protobuf::Arena* arena, const SkillItem& from);
  SkillItem(::google::protobuf::Arena* arena, SkillItem&& from) noexcept
      : SkillItem(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSkillIdFieldNumber = 1,
    kLevelFieldNumber = 2,
    kKeyPosFieldNumber = 3,
  };
  // uint32 skill_id = 1;
  void clear_skill_id() ;
  ::uint32_t skill_id() const;
  void set_skill_id(::uint32_t value);

  private:
  ::uint32_t _internal_skill_id() const;
  void _internal_set_skill_id(::uint32_t value);

  public:
  // int32 level = 2;
  void clear_level() ;
  ::int32_t level() const;
  void set_level(::int32_t value);

  private:
  ::int32_t _internal_level() const;
  void _internal_set_level(::int32_t value);

  public:
  // int32 key_pos = 3;
  void clear_key_pos() ;
  ::int32_t key_pos() const;
  void set_key_pos(::int32_t value);

  private:
  ::int32_t _internal_key_pos() const;
  void _internal_set_key_pos(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:SkillItem)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SkillItem& from_msg);
    ::uint32_t skill_id_;
    ::int32_t level_;
    ::int32_t key_pos_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_base_2eproto;
};
// -------------------------------------------------------------------

class ItemData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ItemData) */ {
 public:
  inline ItemData() : ItemData(nullptr) {}
  ~ItemData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ItemData* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ItemData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ItemData(
      ::google::protobuf::internal::ConstantInitialized);

  inline ItemData(const ItemData& from) : ItemData(nullptr, from) {}
  inline ItemData(ItemData&& from) noexcept
      : ItemData(nullptr, std::move(from)) {}
  inline ItemData& operator=(const ItemData& from) {
    CopyFrom(from);
    return *this;
  }
  inline ItemData& operator=(ItemData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ItemData& default_instance() {
    return *internal_default_instance();
  }
  static inline const ItemData* internal_default_instance() {
    return reinterpret_cast<const ItemData*>(
        &_ItemData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ItemData& a, ItemData& b) { a.Swap(&b); }
  inline void Swap(ItemData* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ItemData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ItemData* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ItemData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ItemData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ItemData& from) { ItemData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ItemData* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ItemData"; }

 protected:
  explicit ItemData(::google::protobuf::Arena* arena);
  ItemData(::google::protobuf::Arena* arena, const ItemData& from);
  ItemData(::google::protobuf::Arena* arena, ItemData&& from) noexcept
      : ItemData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kItemIdFieldNumber = 1,
    kItemNumFieldNumber = 2,
  };
  // int32 item_id = 1;
  void clear_item_id() ;
  ::int32_t item_id() const;
  void set_item_id(::int32_t value);

  private:
  ::int32_t _internal_item_id() const;
  void _internal_set_item_id(::int32_t value);

  public:
  // int32 item_num = 2;
  void clear_item_num() ;
  ::int32_t item_num() const;
  void set_item_num(::int32_t value);

  private:
  ::int32_t _internal_item_num() const;
  void _internal_set_item_num(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:ItemData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ItemData& from_msg);
    ::int32_t item_id_;
    ::int32_t item_num_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_base_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ItemData

// int32 item_id = 1;
inline void ItemData::clear_item_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.item_id_ = 0;
}
inline ::int32_t ItemData::item_id() const {
  // @@protoc_insertion_point(field_get:ItemData.item_id)
  return _internal_item_id();
}
inline void ItemData::set_item_id(::int32_t value) {
  _internal_set_item_id(value);
  // @@protoc_insertion_point(field_set:ItemData.item_id)
}
inline ::int32_t ItemData::_internal_item_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.item_id_;
}
inline void ItemData::_internal_set_item_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.item_id_ = value;
}

// int32 item_num = 2;
inline void ItemData::clear_item_num() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.item_num_ = 0;
}
inline ::int32_t ItemData::item_num() const {
  // @@protoc_insertion_point(field_get:ItemData.item_num)
  return _internal_item_num();
}
inline void ItemData::set_item_num(::int32_t value) {
  _internal_set_item_num(value);
  // @@protoc_insertion_point(field_set:ItemData.item_num)
}
inline ::int32_t ItemData::_internal_item_num() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.item_num_;
}
inline void ItemData::_internal_set_item_num(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.item_num_ = value;
}

// -------------------------------------------------------------------

// SkillItem

// uint32 skill_id = 1;
inline void SkillItem::clear_skill_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.skill_id_ = 0u;
}
inline ::uint32_t SkillItem::skill_id() const {
  // @@protoc_insertion_point(field_get:SkillItem.skill_id)
  return _internal_skill_id();
}
inline void SkillItem::set_skill_id(::uint32_t value) {
  _internal_set_skill_id(value);
  // @@protoc_insertion_point(field_set:SkillItem.skill_id)
}
inline ::uint32_t SkillItem::_internal_skill_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.skill_id_;
}
inline void SkillItem::_internal_set_skill_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.skill_id_ = value;
}

// int32 level = 2;
inline void SkillItem::clear_level() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = 0;
}
inline ::int32_t SkillItem::level() const {
  // @@protoc_insertion_point(field_get:SkillItem.level)
  return _internal_level();
}
inline void SkillItem::set_level(::int32_t value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:SkillItem.level)
}
inline ::int32_t SkillItem::_internal_level() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.level_;
}
inline void SkillItem::_internal_set_level(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = value;
}

// int32 key_pos = 3;
inline void SkillItem::clear_key_pos() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_pos_ = 0;
}
inline ::int32_t SkillItem::key_pos() const {
  // @@protoc_insertion_point(field_get:SkillItem.key_pos)
  return _internal_key_pos();
}
inline void SkillItem::set_key_pos(::int32_t value) {
  _internal_set_key_pos(value);
  // @@protoc_insertion_point(field_set:SkillItem.key_pos)
}
inline ::int32_t SkillItem::_internal_key_pos() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.key_pos_;
}
inline void SkillItem::_internal_set_key_pos(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_pos_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // base_2eproto_2epb_2eh
