// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: define.proto
// Protobuf C++ Version: 5.29.5

#include "define.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_define_2eproto[19];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_define_2eproto = nullptr;
const ::uint32_t TableStruct_define_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_define_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014define.proto*\261\001\n\nObjectType\022\017\n\013object_"
    "none\020\000\022\021\n\robject_player\020\001\022\016\n\nobject_npc\020"
    "\002\022\022\n\016object_monster\020\003\022\016\n\nobject_pet\020\004\022\020\n"
    "\014object_mount\020\005\022\022\n\016object_machine\020\006\022\022\n\016o"
    "bject_partner\020\007\022\021\n\robject_summon\020\010*\300\002\n\nA"
    "ctionType\022\017\n\013action_none\020\000\022\017\n\013action_idl"
    "e\020\001\022\023\n\017action_fix_body\020\002\022\017\n\013action_walk\020"
    "\003\022\016\n\naction_run\020\004\022\016\n\naction_fly\020\005\022\020\n\014act"
    "ion_skill\020\006\022\017\n\013action_mine\020\007\022\017\n\013action_r"
    "oll\020\010\022\017\n\013action_jump\020\t\022\017\n\013action_born\020\n\022"
    "\020\n\014action_dance\020\013\022\017\n\013action_dead\020\014\022\020\n\014ac"
    "tion_wound\020\r\022\024\n\020action_beat_back\020\016\022\024\n\020ac"
    "tion_beat_down\020\017\022\023\n\017action_beat_fly\020\020*q\n"
    "\014ActionStatus\022\026\n\022action_status_none\020\000\022\026\n"
    "\022action_status_hurt\020\001\022\027\n\023action_status_s"
    "tart\020\002\022\030\n\021action_status_end\020\377\377\377\177*x\n\010Copy"
    "Type\022\r\n\tcopy_none\020\000\022\016\n\ncopy_login\020\001\022\021\n\rc"
    "opy_sel_role\020\002\022\r\n\tcopy_city\020\003\022\r\n\tcopy_ma"
    "in\020\004\022\016\n\ncopy_world\020\005\022\014\n\010copy_end\020d*\263\001\n\014O"
    "bjectStatus\022\017\n\013status_none\020\000\022\017\n\013status_d"
    "ead\020\001\022\023\n\017status_not_move\020\002\022\023\n\017status_not"
    "_cast\020\003\022\026\n\022status_not_be_hurt\020\004\022\031\n\025statu"
    "s_not_be_control\020\005\022\022\n\016status_stealth\020\006\022\020"
    "\n\014status_blind\020\007*\207\002\n\010ItemType\022\r\n\titem_no"
    "ne\020\000\022\016\n\nitem_money\020\001\022\017\n\013item_action\020\002\022\r\n"
    "\titem_item\020\003\022\016\n\nitem_equip\020\004\022\014\n\010item_gem"
    "\020\005\022\017\n\013item_relics\020\006\022\016\n\nitem_mount\020\007\022\014\n\010i"
    "tem_pet\020\010\022\020\n\014item_partner\020\t\022\020\n\014item_fash"
    "ion\020\n\022\014\n\010item_box\020\013\022\020\n\014item_act_box\020\014\022\r\n"
    "\titem_chip\020\r\022\r\n\titem_rune\020\016\022\r\n\titem_drug"
    "\020\017*\211\001\n\007BagType\022\014\n\010bag_none\020\000\022\014\n\010bag_item"
    "\020\001\022\013\n\007bag_gem\020\002\022\017\n\013bag_fashion\020\003\022\014\n\010bag_"
    "chip\020\004\022\014\n\010bag_rune\020\005\022\014\n\010bag_task\020\006\022\014\n\010ba"
    "g_soul\020\007\022\014\n\010bag_card\020\010*3\n\014FunctionType\022\021"
    "\n\rfunc_begin_id\020\000\022\020\n\013func_end_id\020\226\001*\263\002\n\006"
    "AttrId\022\013\n\007attr_hp\020\000\022\013\n\007attr_mp\020\001\022\017\n\013attr"
    "_hp_max\020\002\022\017\n\013attr_mp_max\020\003\022\016\n\nattr_speed"
    "\020\004\022\017\n\013attr_attack\020\005\022\020\n\014attr_element\020\006\022\022\n"
    "\016attr_magic_def\020\007\022\023\n\017attr_physic_def\020\010\022\021"
    "\n\rattr_hit_rate\020\t\022\016\n\nattr_dodge\020\n\022\022\n\016att"
    "r_more_hurt\020\013\022\022\n\016attr_less_hurt\020\014\022\021\n\ratt"
    "r_crit_hit\020\r\022\021\n\rattr_crit_def\020\016\022\022\n\016attr_"
    "crit_hurt\020\017\022\014\n\010attr_num\020\020*A\n\014ShipRelatio"
    "n\022\020\n\014ship_neutral\020\000\022\017\n\013ship_friend\020\001\022\016\n\n"
    "ship_enemy\020\002*9\n\013HitShipType\022\013\n\007hit_all\020\000"
    "\022\016\n\nhit_friend\020\001\022\r\n\thit_enemy\020\002*\031\n\010BuffT"
    "ype\022\r\n\tbuff_none\020\000*a\n\013ChatChannel\022\r\n\tcha"
    "t_none\020\000\022\016\n\nchat_world\020\001\022\020\n\014chat_private"
    "\020\002\022\016\n\nchat_guild\020\003\022\021\n\rchat_roll_tip\020\004*\251\001"
    "\n\010EquipPos\022\016\n\nequip_none\020\000\022\020\n\014equip_helm"
    "et\020\001\022\022\n\016equip_necklace\020\002\022\017\n\013equip_armor\020"
    "\003\022\017\n\013equip_shoes\020\004\022\017\n\013equip_wrist\020\005\022\016\n\ne"
    "quip_ring\020\006\022\022\n\016equip_talisman\020\007\022\020\n\014equip"
    "_weapon\020\010*N\n\nTaskStatus\022\r\n\ttask_init\020\000\022\017"
    "\n\013task_accept\020\001\022\017\n\013task_finish\020\002\022\017\n\013task"
    "_commit\020\003*N\n\nCopyResult\022\024\n\020copy_none_res"
    "ult\020\000\022\014\n\010copy_win\020\001\022\r\n\tcopy_lost\020\002\022\r\n\tco"
    "py_draw\020\003*E\n\010GuildPos\022\020\n\014guild_member\020\000\022"
    "\020\n\014guild_leader\020\001\022\025\n\021guild_vice_leader\020\002"
    "*+\n\010MailType\022\016\n\nmail_begin\020\000\022\017\n\013mail_cus"
    "tom\020\001*-\n\nMailStatus\022\014\n\010mail_new\020\000\022\021\n\rmai"
    "l_received\020\001b\006proto3"
};
static ::absl::once_flag descriptor_table_define_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_define_2eproto = {
    false,
    false,
    2460,
    descriptor_table_protodef_define_2eproto,
    "define.proto",
    &descriptor_table_define_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_define_2eproto::offsets,
    file_level_enum_descriptors_define_2eproto,
    file_level_service_descriptors_define_2eproto,
};
const ::google::protobuf::EnumDescriptor* ObjectType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ObjectType_internal_data_[] = {
    589824u, 0u, };
bool ObjectType_IsValid(int value) {
  return 0 <= value && value <= 8;
}
const ::google::protobuf::EnumDescriptor* ActionType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t ActionType_internal_data_[] = {
    1114112u, 0u, };
bool ActionType_IsValid(int value) {
  return 0 <= value && value <= 16;
}
const ::google::protobuf::EnumDescriptor* ActionStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t ActionStatus_internal_data_[] = {
    196608u, 65536u, 268435455u, };
bool ActionStatus_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, ActionStatus_internal_data_);
}
const ::google::protobuf::EnumDescriptor* CopyType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[3];
}
PROTOBUF_CONSTINIT const uint32_t CopyType_internal_data_[] = {
    393216u, 65536u, 100u, };
bool CopyType_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, CopyType_internal_data_);
}
const ::google::protobuf::EnumDescriptor* ObjectStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[4];
}
PROTOBUF_CONSTINIT const uint32_t ObjectStatus_internal_data_[] = {
    524288u, 0u, };
bool ObjectStatus_IsValid(int value) {
  return 0 <= value && value <= 7;
}
const ::google::protobuf::EnumDescriptor* ItemType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[5];
}
PROTOBUF_CONSTINIT const uint32_t ItemType_internal_data_[] = {
    1048576u, 0u, };
bool ItemType_IsValid(int value) {
  return 0 <= value && value <= 15;
}
const ::google::protobuf::EnumDescriptor* BagType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[6];
}
PROTOBUF_CONSTINIT const uint32_t BagType_internal_data_[] = {
    589824u, 0u, };
bool BagType_IsValid(int value) {
  return 0 <= value && value <= 8;
}
const ::google::protobuf::EnumDescriptor* FunctionType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[7];
}
PROTOBUF_CONSTINIT const uint32_t FunctionType_internal_data_[] = {
    65536u, 65536u, 150u, };
bool FunctionType_IsValid(int value) {
  return ::_pbi::ValidateEnum(value, FunctionType_internal_data_);
}
const ::google::protobuf::EnumDescriptor* AttrId_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[8];
}
PROTOBUF_CONSTINIT const uint32_t AttrId_internal_data_[] = {
    1114112u, 0u, };
bool AttrId_IsValid(int value) {
  return 0 <= value && value <= 16;
}
const ::google::protobuf::EnumDescriptor* ShipRelation_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[9];
}
PROTOBUF_CONSTINIT const uint32_t ShipRelation_internal_data_[] = {
    196608u, 0u, };
bool ShipRelation_IsValid(int value) {
  return 0 <= value && value <= 2;
}
const ::google::protobuf::EnumDescriptor* HitShipType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[10];
}
PROTOBUF_CONSTINIT const uint32_t HitShipType_internal_data_[] = {
    196608u, 0u, };
bool HitShipType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
const ::google::protobuf::EnumDescriptor* BuffType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[11];
}
PROTOBUF_CONSTINIT const uint32_t BuffType_internal_data_[] = {
    65536u, 0u, };
bool BuffType_IsValid(int value) {
  return 0 <= value && value <= 0;
}
const ::google::protobuf::EnumDescriptor* ChatChannel_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[12];
}
PROTOBUF_CONSTINIT const uint32_t ChatChannel_internal_data_[] = {
    327680u, 0u, };
bool ChatChannel_IsValid(int value) {
  return 0 <= value && value <= 4;
}
const ::google::protobuf::EnumDescriptor* EquipPos_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[13];
}
PROTOBUF_CONSTINIT const uint32_t EquipPos_internal_data_[] = {
    589824u, 0u, };
bool EquipPos_IsValid(int value) {
  return 0 <= value && value <= 8;
}
const ::google::protobuf::EnumDescriptor* TaskStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[14];
}
PROTOBUF_CONSTINIT const uint32_t TaskStatus_internal_data_[] = {
    262144u, 0u, };
bool TaskStatus_IsValid(int value) {
  return 0 <= value && value <= 3;
}
const ::google::protobuf::EnumDescriptor* CopyResult_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[15];
}
PROTOBUF_CONSTINIT const uint32_t CopyResult_internal_data_[] = {
    262144u, 0u, };
bool CopyResult_IsValid(int value) {
  return 0 <= value && value <= 3;
}
const ::google::protobuf::EnumDescriptor* GuildPos_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[16];
}
PROTOBUF_CONSTINIT const uint32_t GuildPos_internal_data_[] = {
    196608u, 0u, };
bool GuildPos_IsValid(int value) {
  return 0 <= value && value <= 2;
}
const ::google::protobuf::EnumDescriptor* MailType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[17];
}
PROTOBUF_CONSTINIT const uint32_t MailType_internal_data_[] = {
    131072u, 0u, };
bool MailType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
const ::google::protobuf::EnumDescriptor* MailStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_define_2eproto);
  return file_level_enum_descriptors_define_2eproto[18];
}
PROTOBUF_CONSTINIT const uint32_t MailStatus_internal_data_[] = {
    131072u, 0u, };
bool MailStatus_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_define_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
