# ======================= spdlog pattern 占位符速查表 =======================
# 时间
# %Y 年(4位)     %y 年(2位)     %m 月(01-12)    %d 日(01-31)
# %H 时(00-23)   %I 时(01-12)   %M 分(00-59)    %S 秒(00-59)
# %e 毫秒        %f 微秒        %F 纳秒         %z 时区偏移
# %+ ISO8601完整时间  例如 2025-08-11T21:07:45+08:00
#
# 日志级别
# %l 小写日志级别 (info)    %L 大写日志级别 (INFO)
# %^ 开启颜色    %$ 关闭颜色（通常包裹日志级别）
#
# 线程/进程
# %t 线程ID      %P 进程ID
#
# 日志器/消息
# %n 日志器名称   %v 日志消息     %V 原始消息（无颜色）
#
# 源代码信息（需SPDLOG_ACTIVE_LEVEL支持）
# %s 文件名      %g 文件路径     %# 行号     %! 函数名
#
# 其他
# %% 输出百分号   %o 日志顺序号   %i 日志ID(每logger独立)
# %p 进程名（部分平台支持）
loggers:
  - name: "sys"
    async: true
    queue_size: 8192
    thread_count: 1
    overflow_policy: block
    level: info
    pattern: "[%H:%M:%S %z] [%^%l%$] %v"
    sinks:
      - type: console
        color: true
      - type: file
        path: "logs/main.log"
        truncate: false

  - name: "audit"
    async: false
    level: warn
    sinks:
      - type: file
        path: "logs/audit.log"
        truncate: true
